# Generated by Django 4.2.5 on 2023-09-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=17, unique=True, verbose_name='telefon'),
        ),
    ]
